name: Deploy backend to Azure
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with soruce code
    defaults:
      run:
        working-directory: "backend/main-backend"
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"

      - name: maven build, clean
        run: |
          mvn clean package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print test
        id: pull-request-coverage
        run: |
          echo ${{env}}
          echo ${{inputs.environment}}
          echo ${{inputs.environment.env.AZURE_MAIN_BACKEND_APP_NAME}}
          echo ${{inputs.environment.AZURE_MAIN_BACKEND_APP_NAME}}
          echo ${{env.AZURE_MAIN_BACKEND_APP_NAME}}
          echo ${{env[inputs.environment]}}
          echo ${{env[inputs.environment].AZURE_MAIN_BACKEND_APP_NAME}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env[inputs.environment].AZURE_MAIN_BACKEND_APP_NAME }}
          package: "*.jar"
